version: "3.7"

services:
    db:
        image: mongo:6.0.3
        ports:
          - "27017:27017"
        networks:
            - mernapp
        volumes:
            - db-data:/data/db   
    backend:
        build: 
          context: ./backend 
        restart: always
        depends_on:
            - db
        ports:
            - "5000:5000"
        networks:
            - mernapp
    frontend:
        build: ./frontend/
        restart: always
        depends_on:
            - backend
        ports:
            - "3000:3000"
        networks:
            - mernapp

networks:
    mernapp:
        driver: bridge

volumes:
    db-data: