apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: search
  name: mern-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: search
    spec:
      containers:
      - image: infotechia/mern-backend
        name: search
        ports:
          - containerPort: 5000